### ISSUE TITLE
Does mixwith detect and cache sub chains?

### ISSUE THREAD

**Issue by trusktr** [justinfagnani/mixwith.js#15]
For example, suppose I have

```js
class Scene extends mix(ImperativeBase).with(TreeNode) {
  // ...
}

class Node extends mix(ImperativeBase).with(TreeNode, Transformable) {
  // ...
}

class SomethingElse extends mix(TreeNode).with(Transformable) {
  // ...
}
```

Is mixwith.js smart enough to re-use the `ImperativeBase -> TreeNode` chain between the `Scene` and `Node` classes, and the `TreeNode -> Transformable` chain between the `Node` and `SomethingElse` classes?

**Comment by justinfagnani** [comment]
`mix(S).with(A, B)` is just sugar for `B(A(S))`, so it doesn't cache subchains, but `Cached` makes a mixin function handle caching itself, regardless of whether `mix()` is used.

```javascript
const TreeNode = Cached(BareMixin((superclass) => class extends superclass { ... }));

class Scene extends mix(ImperativeBase).with(TreeNode) { ... }

class Node extends Transformable(TreeNode(ImperativeBase)) { ... }
```

A single `ImperativeBase -> TreeNode` is reused in `Scene` and `Node`.
