### ISSUE TITLE
New mixin base on existing class

### ISSUE THREAD

**Issue by atoumbre** [justinfagnani/mixwith.js#16]
Hello @justinfagnani 

Is it possible to use your mixwith to create a class factory mixin based  an existing class (like Node EventEmitter) and use it with mix ?

**Comment by minecrawler** [comment]
I think, you might have to make a wrapper-Mixin, as `EventEmitter` was not created as a Mixin.

**Comment by justinfagnani** [comment]
@minecrawler is correct. Without accepting a superclass as a parameter, there's no way to apply a class as a mixin. This would be a great language feature though, and compilers could do interesting things too.

**Comment by khusamov** [comment]
@minecrawler How to make a wrapper-Mixin? Can I ask for an example code?
