### ISSUE TITLE
How do i import `mix` (ES6) ?

### ISSUE THREAD

**Issue by alexandru-tomescu** [justinfagnani/mixwith.js#33]
Hi, i'm trying already for a while to implement an utility to extend an LitElement with multiple classes that adds functionalities to it, but i want to avoid to create a mixin for every of these classes and execute them when extending. I want a simpler solution like yours seems to be.

The problem it's that i'm not able to import `mix`, neither `import { mix } from 'mixwith';` or `import  mix from 'mixwith';` are working. I'm getting an error like this:
`Uncaught (in promise) SyntaxError: The requested module '../../node_modules/mixwith/mixwith.js' does not provide an export named 'mix'`

Can you please help me out ? Thanks

**Comment by 1point7point4** [comment]
I took a little peek into the source (which can be found at `this-part-will-vary-but-you-can-try-the-character-"~"-and-hope-that-works/node_modules/mixwith/mixwith.js`), and it seems like mixwith doesn't support es6 import syntax (what you're trying to use). This really shouldn't be a surpriseWhat you want to do instead is something along the lines of:
```javascript
const mixwith = require('mixwith')
// Code using mixwith goes here.
```
You can go [here](https://nodejs.org/api/modules.html) for more information.

**Comment by alexandru-tomescu** [comment]
Thank you for the response, but no i'm extending a class with a mixin at a time and the issue was related only to frontend development (node.js not there). I think this can be closed.
