### ISSUE TITLE
instanceof check with multiple mixins

### ISSUE THREAD

**Issue by allmarkedup** [justinfagnani/mixwith.js#9]
Hi - I'm just exploring this way of implementing mixins and I'm really liking it. However one thing that I've noticed is that the `instanceof`check doesn't work as I expected when using multiple mixins when doing something like:

```
class D extends mix(A).with(B, C)
```

In this case `D instanceof B` will be true, however `D instanceof C` will be false.

Is there any way to work around this? Or have I misunderstood how the @@ hasInstance support is supposed to work?

**Comment by justinfagnani** [comment]
`@@hasInstance` support isn't very available yet. In the meantime I've added the function `hasMixin(obj, mixin)`.
